export const FETCH_WALLPAPERS = "FETCH_WALLPAPERS";
export const FETCH_WALLPAPERS_BY_CATEGORY = "FETCH_WALLPAPERS_BY_CATEGORY";
export const CLEAR_DATA = 'CLEAR_DATA'
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const CHANGE_MODAL_VISIBILITY = 'CHANGE_MODAL_VISIBILITY';